export const types = {
    GET_ARTICLES: 'GET_ARTICLES',
    CLEAR_ARTICLES: 'CLEAR_ARTICLES',
    GET_VIDEOS: 'GET_VIDEOS',
    CLEAR_VIDEOS: 'CLEAR_VIDEOS',
    GET_COMMENTS: 'GET_COMMENTS',
    CLEAR_COMMENTS: 'CLEAR_COMMENTS',
    SET_ERRORS: 'SET_ERRORS',
    CLEAR_ERRORS: 'CLEAR_ERRORS',
    DETAILS: 'DETAILS',
    CONTENT_TYPE: 'CONTENT_TYPE'
}